/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_aat_layout_feature_type_t : uint
    {
        HB_AAT_LAYOUT_FEATURE_TYPE_INVALID = 0xFFFF,
        HB_AAT_LAYOUT_FEATURE_TYPE_ALL_TYPOGRAPHIC = 0,
        HB_AAT_LAYOUT_FEATURE_TYPE_LIGATURES = 1,
        HB_AAT_LAYOUT_FEATURE_TYPE_CURSIVE_CONNECTION = 2,
        HB_AAT_LAYOUT_FEATURE_TYPE_LETTER_CASE = 3,
        HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_SUBSTITUTION = 4,
        HB_AAT_LAYOUT_FEATURE_TYPE_LINGUISTIC_REARRANGEMENT = 5,
        HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_SPACING = 6,
        HB_AAT_LAYOUT_FEATURE_TYPE_SMART_SWASH_TYPE = 8,
        HB_AAT_LAYOUT_FEATURE_TYPE_DIACRITICS_TYPE = 9,
        HB_AAT_LAYOUT_FEATURE_TYPE_VERTICAL_POSITION = 10,
        HB_AAT_LAYOUT_FEATURE_TYPE_FRACTIONS = 11,
        HB_AAT_LAYOUT_FEATURE_TYPE_OVERLAPPING_CHARACTERS_TYPE = 13,
        HB_AAT_LAYOUT_FEATURE_TYPE_TYPOGRAPHIC_EXTRAS = 14,
        HB_AAT_LAYOUT_FEATURE_TYPE_MATHEMATICAL_EXTRAS = 15,
        HB_AAT_LAYOUT_FEATURE_TYPE_ORNAMENT_SETS_TYPE = 16,
        HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_ALTERNATIVES = 17,
        HB_AAT_LAYOUT_FEATURE_TYPE_DESIGN_COMPLEXITY_TYPE = 18,
        HB_AAT_LAYOUT_FEATURE_TYPE_STYLE_OPTIONS = 19,
        HB_AAT_LAYOUT_FEATURE_TYPE_CHARACTER_SHAPE = 20,
        HB_AAT_LAYOUT_FEATURE_TYPE_NUMBER_CASE = 21,
        HB_AAT_LAYOUT_FEATURE_TYPE_TEXT_SPACING = 22,
        HB_AAT_LAYOUT_FEATURE_TYPE_TRANSLITERATION = 23,
        HB_AAT_LAYOUT_FEATURE_TYPE_ANNOTATION_TYPE = 24,
        HB_AAT_LAYOUT_FEATURE_TYPE_KANA_SPACING_TYPE = 25,
        HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_SPACING_TYPE = 26,
        HB_AAT_LAYOUT_FEATURE_TYPE_UNICODE_DECOMPOSITION_TYPE = 27,
        HB_AAT_LAYOUT_FEATURE_TYPE_RUBY_KANA = 28,
        HB_AAT_LAYOUT_FEATURE_TYPE_CJK_SYMBOL_ALTERNATIVES_TYPE = 29,
        HB_AAT_LAYOUT_FEATURE_TYPE_IDEOGRAPHIC_ALTERNATIVES_TYPE = 30,
        HB_AAT_LAYOUT_FEATURE_TYPE_CJK_VERTICAL_ROMAN_PLACEMENT_TYPE = 31,
        HB_AAT_LAYOUT_FEATURE_TYPE_ITALIC_CJK_ROMAN = 32,
        HB_AAT_LAYOUT_FEATURE_TYPE_CASE_SENSITIVE_LAYOUT = 33,
        HB_AAT_LAYOUT_FEATURE_TYPE_ALTERNATE_KANA = 34,
        HB_AAT_LAYOUT_FEATURE_TYPE_STYLISTIC_ALTERNATIVES = 35,
        HB_AAT_LAYOUT_FEATURE_TYPE_CONTEXTUAL_ALTERNATIVES = 36,
        HB_AAT_LAYOUT_FEATURE_TYPE_LOWER_CASE = 37,
        HB_AAT_LAYOUT_FEATURE_TYPE_UPPER_CASE = 38,
        HB_AAT_LAYOUT_FEATURE_TYPE_LANGUAGE_TAG_TYPE = 39,
        HB_AAT_LAYOUT_FEATURE_TYPE_CJK_ROMAN_SPACING_TYPE = 103,
        _HB_AAT_LAYOUT_FEATURE_TYPE_MAX_VALUE = ((uint)((((uint)(0x7f) & 0xFF) << 24) | (((uint)(0xff) & 0xFF) << 16) | (((uint)(0xff) & 0xFF) << 8) | ((uint)(0xff) & 0xFF))),
    }
}
