/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_buffer_flags_t : uint
    {
        HB_BUFFER_FLAG_DEFAULT = 0x00000000U,
        HB_BUFFER_FLAG_BOT = 0x00000001U,
        HB_BUFFER_FLAG_EOT = 0x00000002U,
        HB_BUFFER_FLAG_PRESERVE_DEFAULT_IGNORABLES = 0x00000004U,
        HB_BUFFER_FLAG_REMOVE_DEFAULT_IGNORABLES = 0x00000008U,
        HB_BUFFER_FLAG_DO_NOT_INSERT_DOTTED_CIRCLE = 0x00000010U,
        HB_BUFFER_FLAG_VERIFY = 0x00000020U,
        HB_BUFFER_FLAG_PRODUCE_UNSAFE_TO_CONCAT = 0x00000040U,
        HB_BUFFER_FLAG_PRODUCE_SAFE_TO_INSERT_TATWEEL = 0x00000080U,
        HB_BUFFER_FLAG_DEFINED = 0x000000FFU,
    }
}
