/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_paint_composite_mode_t : uint
    {
        HB_PAINT_COMPOSITE_MODE_CLEAR,
        HB_PAINT_COMPOSITE_MODE_SRC,
        HB_PAINT_COMPOSITE_MODE_DEST,
        HB_PAINT_COMPOSITE_MODE_SRC_OVER,
        HB_PAINT_COMPOSITE_MODE_DEST_OVER,
        HB_PAINT_COMPOSITE_MODE_SRC_IN,
        HB_PAINT_COMPOSITE_MODE_DEST_IN,
        HB_PAINT_COMPOSITE_MODE_SRC_OUT,
        HB_PAINT_COMPOSITE_MODE_DEST_OUT,
        HB_PAINT_COMPOSITE_MODE_SRC_ATOP,
        HB_PAINT_COMPOSITE_MODE_DEST_ATOP,
        HB_PAINT_COMPOSITE_MODE_XOR,
        HB_PAINT_COMPOSITE_MODE_PLUS,
        HB_PAINT_COMPOSITE_MODE_SCREEN,
        HB_PAINT_COMPOSITE_MODE_OVERLAY,
        HB_PAINT_COMPOSITE_MODE_DARKEN,
        HB_PAINT_COMPOSITE_MODE_LIGHTEN,
        HB_PAINT_COMPOSITE_MODE_COLOR_DODGE,
        HB_PAINT_COMPOSITE_MODE_COLOR_BURN,
        HB_PAINT_COMPOSITE_MODE_HARD_LIGHT,
        HB_PAINT_COMPOSITE_MODE_SOFT_LIGHT,
        HB_PAINT_COMPOSITE_MODE_DIFFERENCE,
        HB_PAINT_COMPOSITE_MODE_EXCLUSION,
        HB_PAINT_COMPOSITE_MODE_MULTIPLY,
        HB_PAINT_COMPOSITE_MODE_HSL_HUE,
        HB_PAINT_COMPOSITE_MODE_HSL_SATURATION,
        HB_PAINT_COMPOSITE_MODE_HSL_COLOR,
        HB_PAINT_COMPOSITE_MODE_HSL_LUMINOSITY,
    }
}
