/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_script_t : uint
    {
        HB_SCRIPT_COMMON = ((uint)((((uint)('Z') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('y') & 0xFF))),
        HB_SCRIPT_INHERITED = ((uint)((((uint)('Z') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_UNKNOWN = ((uint)((((uint)('Z') & 0xFF) << 24) | (((uint)('z') & 0xFF) << 16) | (((uint)('z') & 0xFF) << 8) | ((uint)('z') & 0xFF))),
        HB_SCRIPT_ARABIC = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_ARMENIAN = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('n') & 0xFF))),
        HB_SCRIPT_BENGALI = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_CYRILLIC = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('l') & 0xFF))),
        HB_SCRIPT_DEVANAGARI = ((uint)((((uint)('D') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('v') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_GEORGIAN = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('o') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_GREEK = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('e') & 0xFF) << 8) | ((uint)('k') & 0xFF))),
        HB_SCRIPT_GUJARATI = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('j') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_GURMUKHI = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_HANGUL = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_HAN = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_HEBREW = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('b') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_HIRAGANA = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_KANNADA = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('n') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_KATAKANA = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_LAO = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('o') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_LATIN = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('n') & 0xFF))),
        HB_SCRIPT_MALAYALAM = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_ORIYA = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_TAMIL = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('l') & 0xFF))),
        HB_SCRIPT_TELUGU = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_THAI = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_TIBETAN = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('b') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_BOPOMOFO = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('p') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_BRAILLE = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_CANADIAN_SYLLABICS = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('s') & 0xFF))),
        HB_SCRIPT_CHEROKEE = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('e') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_ETHIOPIC = ((uint)((((uint)('E') & 0xFF) << 24) | (((uint)('t') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_KHMER = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_MONGOLIAN = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_MYANMAR = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_OGHAM = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('g') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_RUNIC = ((uint)((((uint)('R') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_SINHALA = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_SYRIAC = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('c') & 0xFF))),
        HB_SCRIPT_THAANA = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_YI = ((uint)((((uint)('Y') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('i') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_DESERET = ((uint)((((uint)('D') & 0xFF) << 24) | (((uint)('s') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_GOTHIC = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_OLD_ITALIC = ((uint)((((uint)('I') & 0xFF) << 24) | (((uint)('t') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('l') & 0xFF))),
        HB_SCRIPT_BUHID = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_HANUNOO = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_TAGALOG = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('g') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_TAGBANWA = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_CYPRIOT = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('p') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_LIMBU = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_LINEAR_B = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_OSMANYA = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('s') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_SHAVIAN = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('w') & 0xFF))),
        HB_SCRIPT_TAI_LE = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('e') & 0xFF))),
        HB_SCRIPT_UGARITIC = ((uint)((((uint)('U') & 0xFF) << 24) | (((uint)('g') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_BUGINESE = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_COPTIC = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('p') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_GLAGOLITIC = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_KHAROSHTHI = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_NEW_TAI_LUE = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_OLD_PERSIAN = ((uint)((((uint)('X') & 0xFF) << 24) | (((uint)('p') & 0xFF) << 16) | (((uint)('e') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_SYLOTI_NAGRI = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_TIFINAGH = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('f') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_BALINESE = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_CUNEIFORM = ((uint)((((uint)('X') & 0xFF) << 24) | (((uint)('s') & 0xFF) << 16) | (((uint)('u') & 0xFF) << 8) | ((uint)('x') & 0xFF))),
        HB_SCRIPT_NKO = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('k') & 0xFF) << 16) | (((uint)('o') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_PHAGS_PA = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_PHOENICIAN = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('x') & 0xFF))),
        HB_SCRIPT_CARIAN = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_CHAM = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_KAYAH_LI = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_LEPCHA = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('p') & 0xFF) << 8) | ((uint)('c') & 0xFF))),
        HB_SCRIPT_LYCIAN = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('c') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_LYDIAN = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('y') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_OL_CHIKI = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('c') & 0xFF) << 8) | ((uint)('k') & 0xFF))),
        HB_SCRIPT_REJANG = ((uint)((((uint)('R') & 0xFF) << 24) | (((uint)('j') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_SAURASHTRA = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('u') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_SUNDANESE = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_VAI = ((uint)((((uint)('V') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('i') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_AVESTAN = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('v') & 0xFF) << 16) | (((uint)('s') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_BAMUM = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_EGYPTIAN_HIEROGLYPHS = ((uint)((((uint)('E') & 0xFF) << 24) | (((uint)('g') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('p') & 0xFF))),
        HB_SCRIPT_IMPERIAL_ARAMAIC = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_INSCRIPTIONAL_PAHLAVI = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_INSCRIPTIONAL_PARTHIAN = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_JAVANESE = ((uint)((((uint)('J') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('v') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_KAITHI = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('t') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_LISU = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('s') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_MEETEI_MAYEK = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('t') & 0xFF) << 16) | (((uint)('e') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_OLD_SOUTH_ARABIAN = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_OLD_TURKIC = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('k') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_SAMARITAN = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_TAI_THAM = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_TAI_VIET = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('v') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_BATAK = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('k') & 0xFF))),
        HB_SCRIPT_BRAHMI = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_MANDAIC = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_CHAKMA = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('k') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_MEROITIC_CURSIVE = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('c') & 0xFF))),
        HB_SCRIPT_MEROITIC_HIEROGLYPHS = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_MIAO = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_SHARADA = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_SORA_SOMPENG = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_TAKRI = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('k') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_BASSA_VAH = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('s') & 0xFF) << 8) | ((uint)('s') & 0xFF))),
        HB_SCRIPT_CAUCASIAN_ALBANIAN = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('g') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_DUPLOYAN = ((uint)((((uint)('D') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('p') & 0xFF) << 8) | ((uint)('l') & 0xFF))),
        HB_SCRIPT_ELBASAN = ((uint)((((uint)('E') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('b') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_GRANTHA = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('n') & 0xFF))),
        HB_SCRIPT_KHOJKI = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('o') & 0xFF) << 8) | ((uint)('j') & 0xFF))),
        HB_SCRIPT_KHUDAWADI = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_LINEAR_A = ((uint)((((uint)('L') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_MAHAJANI = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('j') & 0xFF))),
        HB_SCRIPT_MANICHAEAN = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_MENDE_KIKAKUI = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_MODI = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_MRO = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('o') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_NABATAEAN = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('b') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_OLD_NORTH_ARABIAN = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_OLD_PERMIC = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_PAHAWH_HMONG = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('m') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_PALMYRENE = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_PAU_CIN_HAU = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('u') & 0xFF) << 8) | ((uint)('c') & 0xFF))),
        HB_SCRIPT_PSALTER_PAHLAVI = ((uint)((((uint)('P') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('p') & 0xFF))),
        HB_SCRIPT_SIDDHAM = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_TIRHUTA = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_WARANG_CITI = ((uint)((((uint)('W') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_AHOM = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('o') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_ANATOLIAN_HIEROGLYPHS = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('u') & 0xFF) << 8) | ((uint)('w') & 0xFF))),
        HB_SCRIPT_HATRAN = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_MULTANI = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_OLD_HUNGARIAN = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_SIGNWRITING = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('g') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('w') & 0xFF))),
        HB_SCRIPT_ADLAM = ((uint)((((uint)('A') & 0xFF) << 24) | (((uint)('d') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_BHAIKSUKI = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('k') & 0xFF) << 8) | ((uint)('s') & 0xFF))),
        HB_SCRIPT_MARCHEN = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('c') & 0xFF))),
        HB_SCRIPT_OSAGE = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('s') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('e') & 0xFF))),
        HB_SCRIPT_TANGUT = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_NEWA = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('w') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_MASARAM_GONDI = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_NUSHU = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('s') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_SOYOMBO = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_ZANABAZAR_SQUARE = ((uint)((((uint)('Z') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('b') & 0xFF))),
        HB_SCRIPT_DOGRA = ((uint)((((uint)('D') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_GUNJALA_GONDI = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_HANIFI_ROHINGYA = ((uint)((((uint)('R') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_MAKASAR = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('k') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_MEDEFAIDRIN = ((uint)((((uint)('M') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('f') & 0xFF))),
        HB_SCRIPT_OLD_SOGDIAN = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_SOGDIAN = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_ELYMAIC = ((uint)((((uint)('E') & 0xFF) << 24) | (((uint)('l') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_NANDINAGARI = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('d') & 0xFF))),
        HB_SCRIPT_NYIAKENG_PUACHUE_HMONG = ((uint)((((uint)('H') & 0xFF) << 24) | (((uint)('m') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('p') & 0xFF))),
        HB_SCRIPT_WANCHO = ((uint)((((uint)('W') & 0xFF) << 24) | (((uint)('c') & 0xFF) << 16) | (((uint)('h') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_CHORASMIAN = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('h') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('s') & 0xFF))),
        HB_SCRIPT_DIVES_AKURU = ((uint)((((uint)('D') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('k') & 0xFF))),
        HB_SCRIPT_KHITAN_SMALL_SCRIPT = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('s') & 0xFF))),
        HB_SCRIPT_YEZIDI = ((uint)((((uint)('Y') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('z') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_CYPRO_MINOAN = ((uint)((((uint)('C') & 0xFF) << 24) | (((uint)('p') & 0xFF) << 16) | (((uint)('m') & 0xFF) << 8) | ((uint)('n') & 0xFF))),
        HB_SCRIPT_OLD_UYGHUR = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_TANGSA = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('n') & 0xFF) << 16) | (((uint)('s') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_TOTO = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_VITHKUQI = ((uint)((((uint)('V') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_MATH = ((uint)((((uint)('Z') & 0xFF) << 24) | (((uint)('m') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_KAWI = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('w') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_NAG_MUNDARI = ((uint)((((uint)('N') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('g') & 0xFF) << 8) | ((uint)('m') & 0xFF))),
        HB_SCRIPT_GARAY = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('a') & 0xFF))),
        HB_SCRIPT_GURUNG_KHEMA = ((uint)((((uint)('G') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('k') & 0xFF) << 8) | ((uint)('h') & 0xFF))),
        HB_SCRIPT_KIRAT_RAI = ((uint)((((uint)('K') & 0xFF) << 24) | (((uint)('r') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('i') & 0xFF))),
        HB_SCRIPT_OL_ONAL = ((uint)((((uint)('O') & 0xFF) << 24) | (((uint)('n') & 0xFF) << 16) | (((uint)('a') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_SUNUWAR = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('n') & 0xFF) << 8) | ((uint)('u') & 0xFF))),
        HB_SCRIPT_TODHRI = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('r') & 0xFF))),
        HB_SCRIPT_TULU_TIGALARI = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('u') & 0xFF) << 16) | (((uint)('t') & 0xFF) << 8) | ((uint)('g') & 0xFF))),
        HB_SCRIPT_BERIA_ERFE = ((uint)((((uint)('B') & 0xFF) << 24) | (((uint)('e') & 0xFF) << 16) | (((uint)('r') & 0xFF) << 8) | ((uint)('f') & 0xFF))),
        HB_SCRIPT_SIDETIC = ((uint)((((uint)('S') & 0xFF) << 24) | (((uint)('i') & 0xFF) << 16) | (((uint)('d') & 0xFF) << 8) | ((uint)('t') & 0xFF))),
        HB_SCRIPT_TAI_YO = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('a') & 0xFF) << 16) | (((uint)('y') & 0xFF) << 8) | ((uint)('o') & 0xFF))),
        HB_SCRIPT_TOLONG_SIKI = ((uint)((((uint)('T') & 0xFF) << 24) | (((uint)('o') & 0xFF) << 16) | (((uint)('l') & 0xFF) << 8) | ((uint)('s') & 0xFF))),
        HB_SCRIPT_INVALID = ((uint)((((uint)(0) & 0xFF) << 24) | (((uint)(0) & 0xFF) << 16) | (((uint)(0) & 0xFF) << 8) | ((uint)(0) & 0xFF))),
        _HB_SCRIPT_MAX_VALUE = ((uint)((((uint)(0x7f) & 0xFF) << 24) | (((uint)(0xff) & 0xFF) << 16) | (((uint)(0xff) & 0xFF) << 8) | ((uint)(0xff) & 0xFF))),
        _HB_SCRIPT_MAX_VALUE_SIGNED = ((uint)((((uint)(0x7f) & 0xFF) << 24) | (((uint)(0xff) & 0xFF) << 16) | (((uint)(0xff) & 0xFF) << 8) | ((uint)(0xff) & 0xFF))),
    }
}
