/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_subset_flags_t : uint
    {
        HB_SUBSET_FLAGS_DEFAULT = 0x00000000U,
        HB_SUBSET_FLAGS_NO_HINTING = 0x00000001U,
        HB_SUBSET_FLAGS_RETAIN_GIDS = 0x00000002U,
        HB_SUBSET_FLAGS_DESUBROUTINIZE = 0x00000004U,
        HB_SUBSET_FLAGS_NAME_LEGACY = 0x00000008U,
        HB_SUBSET_FLAGS_SET_OVERLAPS_FLAG = 0x00000010U,
        HB_SUBSET_FLAGS_PASSTHROUGH_UNRECOGNIZED = 0x00000020U,
        HB_SUBSET_FLAGS_NOTDEF_OUTLINE = 0x00000040U,
        HB_SUBSET_FLAGS_GLYPH_NAMES = 0x00000080U,
        HB_SUBSET_FLAGS_NO_PRUNE_UNICODE_RANGES = 0x00000100U,
        HB_SUBSET_FLAGS_NO_LAYOUT_CLOSURE = 0x00000200U,
        HB_SUBSET_FLAGS_OPTIMIZE_IUP_DELTAS = 0x00000400U,
        HB_SUBSET_FLAGS_NO_BIDI_CLOSURE = 0x00000800U,
    }
}
