/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_unicode_combining_class_t : uint
    {
        HB_UNICODE_COMBINING_CLASS_NOT_REORDERED = 0,
        HB_UNICODE_COMBINING_CLASS_OVERLAY = 1,
        HB_UNICODE_COMBINING_CLASS_NUKTA = 7,
        HB_UNICODE_COMBINING_CLASS_KANA_VOICING = 8,
        HB_UNICODE_COMBINING_CLASS_VIRAMA = 9,
        HB_UNICODE_COMBINING_CLASS_CCC10 = 10,
        HB_UNICODE_COMBINING_CLASS_CCC11 = 11,
        HB_UNICODE_COMBINING_CLASS_CCC12 = 12,
        HB_UNICODE_COMBINING_CLASS_CCC13 = 13,
        HB_UNICODE_COMBINING_CLASS_CCC14 = 14,
        HB_UNICODE_COMBINING_CLASS_CCC15 = 15,
        HB_UNICODE_COMBINING_CLASS_CCC16 = 16,
        HB_UNICODE_COMBINING_CLASS_CCC17 = 17,
        HB_UNICODE_COMBINING_CLASS_CCC18 = 18,
        HB_UNICODE_COMBINING_CLASS_CCC19 = 19,
        HB_UNICODE_COMBINING_CLASS_CCC20 = 20,
        HB_UNICODE_COMBINING_CLASS_CCC21 = 21,
        HB_UNICODE_COMBINING_CLASS_CCC22 = 22,
        HB_UNICODE_COMBINING_CLASS_CCC23 = 23,
        HB_UNICODE_COMBINING_CLASS_CCC24 = 24,
        HB_UNICODE_COMBINING_CLASS_CCC25 = 25,
        HB_UNICODE_COMBINING_CLASS_CCC26 = 26,
        HB_UNICODE_COMBINING_CLASS_CCC27 = 27,
        HB_UNICODE_COMBINING_CLASS_CCC28 = 28,
        HB_UNICODE_COMBINING_CLASS_CCC29 = 29,
        HB_UNICODE_COMBINING_CLASS_CCC30 = 30,
        HB_UNICODE_COMBINING_CLASS_CCC31 = 31,
        HB_UNICODE_COMBINING_CLASS_CCC32 = 32,
        HB_UNICODE_COMBINING_CLASS_CCC33 = 33,
        HB_UNICODE_COMBINING_CLASS_CCC34 = 34,
        HB_UNICODE_COMBINING_CLASS_CCC35 = 35,
        HB_UNICODE_COMBINING_CLASS_CCC36 = 36,
        HB_UNICODE_COMBINING_CLASS_CCC84 = 84,
        HB_UNICODE_COMBINING_CLASS_CCC91 = 91,
        HB_UNICODE_COMBINING_CLASS_CCC103 = 103,
        HB_UNICODE_COMBINING_CLASS_CCC107 = 107,
        HB_UNICODE_COMBINING_CLASS_CCC118 = 118,
        HB_UNICODE_COMBINING_CLASS_CCC122 = 122,
        HB_UNICODE_COMBINING_CLASS_CCC129 = 129,
        HB_UNICODE_COMBINING_CLASS_CCC130 = 130,
        HB_UNICODE_COMBINING_CLASS_CCC132 = 132,
        HB_UNICODE_COMBINING_CLASS_ATTACHED_BELOW_LEFT = 200,
        HB_UNICODE_COMBINING_CLASS_ATTACHED_BELOW = 202,
        HB_UNICODE_COMBINING_CLASS_ATTACHED_ABOVE = 214,
        HB_UNICODE_COMBINING_CLASS_ATTACHED_ABOVE_RIGHT = 216,
        HB_UNICODE_COMBINING_CLASS_BELOW_LEFT = 218,
        HB_UNICODE_COMBINING_CLASS_BELOW = 220,
        HB_UNICODE_COMBINING_CLASS_BELOW_RIGHT = 222,
        HB_UNICODE_COMBINING_CLASS_LEFT = 224,
        HB_UNICODE_COMBINING_CLASS_RIGHT = 226,
        HB_UNICODE_COMBINING_CLASS_ABOVE_LEFT = 228,
        HB_UNICODE_COMBINING_CLASS_ABOVE = 230,
        HB_UNICODE_COMBINING_CLASS_ABOVE_RIGHT = 232,
        HB_UNICODE_COMBINING_CLASS_DOUBLE_BELOW = 233,
        HB_UNICODE_COMBINING_CLASS_DOUBLE_ABOVE = 234,
        HB_UNICODE_COMBINING_CLASS_IOTA_SUBSCRIPT = 240,
        HB_UNICODE_COMBINING_CLASS_INVALID = 255,
    }
}
