/*
 * Copyright © 2009  Red Hat, Inc.
 *
 * Permission is hereby granted, without written agreement and without
 * license or royalty fees, to use, copy, modify, and distribute this
 * software and its documentation for any purpose, provided that the
 * above copyright notice and the following two paragraphs appear in
 * all copies of this software.
 *
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES
 * ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN
 * IF THE COPYRIGHT HOLDER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * THE COPYRIGHT HOLDER SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING,
 * BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE COPYRIGHT HOLDER HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 */

namespace HarfBuzz.PInvoke
{
    [NativeTypeName("unsigned int")]
    public enum hb_unicode_general_category_t : uint
    {
        HB_UNICODE_GENERAL_CATEGORY_CONTROL,
        HB_UNICODE_GENERAL_CATEGORY_FORMAT,
        HB_UNICODE_GENERAL_CATEGORY_UNASSIGNED,
        HB_UNICODE_GENERAL_CATEGORY_PRIVATE_USE,
        HB_UNICODE_GENERAL_CATEGORY_SURROGATE,
        HB_UNICODE_GENERAL_CATEGORY_LOWERCASE_LETTER,
        HB_UNICODE_GENERAL_CATEGORY_MODIFIER_LETTER,
        HB_UNICODE_GENERAL_CATEGORY_OTHER_LETTER,
        HB_UNICODE_GENERAL_CATEGORY_TITLECASE_LETTER,
        HB_UNICODE_GENERAL_CATEGORY_UPPERCASE_LETTER,
        HB_UNICODE_GENERAL_CATEGORY_SPACING_MARK,
        HB_UNICODE_GENERAL_CATEGORY_ENCLOSING_MARK,
        HB_UNICODE_GENERAL_CATEGORY_NON_SPACING_MARK,
        HB_UNICODE_GENERAL_CATEGORY_DECIMAL_NUMBER,
        HB_UNICODE_GENERAL_CATEGORY_LETTER_NUMBER,
        HB_UNICODE_GENERAL_CATEGORY_OTHER_NUMBER,
        HB_UNICODE_GENERAL_CATEGORY_CONNECT_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_DASH_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_CLOSE_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_FINAL_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_INITIAL_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_OTHER_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_OPEN_PUNCTUATION,
        HB_UNICODE_GENERAL_CATEGORY_CURRENCY_SYMBOL,
        HB_UNICODE_GENERAL_CATEGORY_MODIFIER_SYMBOL,
        HB_UNICODE_GENERAL_CATEGORY_MATH_SYMBOL,
        HB_UNICODE_GENERAL_CATEGORY_OTHER_SYMBOL,
        HB_UNICODE_GENERAL_CATEGORY_LINE_SEPARATOR,
        HB_UNICODE_GENERAL_CATEGORY_PARAGRAPH_SEPARATOR,
        HB_UNICODE_GENERAL_CATEGORY_SPACE_SEPARATOR,
    }
}
